// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes a kidney CT scan image to predict the kidney condition.
 *
 * - analyzeCTScan - A function that handles the CT scan analysis process.
 * - AnalyzeCTScanInput - The input type for the analyzeCTScan function.
 * - AnalyzeCTScanOutput - The return type for the analyzeCTScan function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AnalyzeCTScanInputSchema = z.object({
  ctScanUrl: z.string().describe('The URL of the kidney CT scan image.'),
});
export type AnalyzeCTScanInput = z.infer<typeof AnalyzeCTScanInputSchema>;

const AnalyzeCTScanOutputSchema = z.object({
  condition: z
    .enum(['cyst', 'tumor', 'stone', 'normal'])
    .describe('The predicted kidney condition.'),
  confidenceLevel: z
    .number()
    .min(0)
    .max(1)
    .describe('The confidence level of the prediction (0 to 1).'),
  analytics: z.string().describe('Analytics based on the CT scan image'),
});
export type AnalyzeCTScanOutput = z.infer<typeof AnalyzeCTScanOutputSchema>;

export async function analyzeCTScan(input: AnalyzeCTScanInput): Promise<AnalyzeCTScanOutput> {
  return analyzeCTScanFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeCTScanPrompt',
  input: {
    schema: z.object({
      ctScanUrl: z.string().describe('The URL of the kidney CT scan image.'),
    }),
  },
  output: {
    schema: z.object({
      condition: z
        .enum(['cyst', 'tumor', 'stone', 'normal'])
        .describe('The predicted kidney condition.'),
      confidenceLevel: z
        .number()
        .min(0)
        .max(1)
        .describe('The confidence level of the prediction (0 to 1).'),
      analytics: z.string().describe('Analytics based on the CT scan image'),
    }),
  },
  prompt: `You are a medical AI assistant specializing in analyzing kidney CT scans. Analyze the provided CT scan image and predict the kidney condition.

  Consider the following characteristics when determining the condition:

  - Cyst: Usually round or oval-shaped, with smooth borders and fluid-filled appearance.
  - Tumor: Irregular shape, may have solid components, and can distort the kidney's normal structure.
  - Stone: High density, appears very bright on the CT scan, and has a well-defined shape.
  - Normal: Kidney appears healthy with no abnormalities.

  Return the predicted condition as one of the following values: cyst, tumor, stone, normal.
  Also, return a confidence level between 0 and 1 for your prediction.
  Also, generate some relevant analytics based on the CT scan image, including size, location, and any other notable features.

  CT Scan Image: {{media url=ctScanUrl}}
  `, 
});

const analyzeCTScanFlow = ai.defineFlow<
  typeof AnalyzeCTScanInputSchema,
  typeof AnalyzeCTScanOutputSchema
>(
  {
    name: 'analyzeCTScanFlow',
    inputSchema: AnalyzeCTScanInputSchema,
    outputSchema: AnalyzeCTScanOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
